version: "3.9"
services:

  cassandra-text-matching-seed:
    container_name: cassandra-text-matching-seed
    image: cassandra:4.1.0
    hostname: cassandra-node1
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra1:/var/lib/cassandra

  init-cassandra-keyspace:
    image: cassandra:4.1.0
    depends_on:
      - cassandra-text-matching-seed
    restart: "no"
    entrypoint: [ "/init_keyspace.sh" ]
    volumes:
      - ./cassandra/init_keyspace.sh:/init_keyspace.sh

  rabbitmq-1:
    container_name: "rabbitmq-1"
    image: rabbitmq:3.11.10-management-alpine
    hostname: rabbitmq-1
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitMqUser
      - RABBITMQ_DEFAULT_PASS=rabbitMqPassword
      - RABBITMQ_ERLANG_COOKIE=rabbit-mq-cluster
    ports:
      - "5672:5672"
      - "15672:15672"


